Add Missing Type Annotations
adafruit/Adafruit_CircuitPython_US100 pull request #17
Opened 2022-09-02 17:33 UTC by tcfranks

resolves #16 
submitted for review / comment

2022-09-02 19:37 UTC, tekktrik requested changes

2022-09-02 19:37 UTC, tekktrik commented on adafruit_us100.py
> +    def distance(self) -> float:
Since this can return `None`, it should be `Optional[float]`.  Can you correct the docstring too? Thanks!

2022-09-02 19:37 UTC, tekktrik commented on adafruit_us100.py
> +    def __init__(self, uart: UART):
Don't forget the `None` return type!

2022-09-02 19:37 UTC, tekktrik commented on adafruit_us100.py
> +    def temperature(self) -> Union[None, int]:
Can you change this to `Optional[int]`?

2022-09-02 19:50 UTC, tcfranks commented on adafruit_us100.py
> +    def __init__(self, uart: UART):
oops!

2022-09-02 20:26 UTC, tekktrik requested changes

2022-09-02 20:26 UTC, tekktrik commented on adafruit_us100.py
> +    def distance(self) -> Optional[float]:
Please correct the docstring return to match!

2022-09-03 16:25 UTC, tekktrik approved these changes
Thanks, nice work!

2022-09-03 16:25 UTC, merged